### ISSUE TITLE
running script fails with "UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 111: ordinal not in range(128)"

### ISSUE THREAD

**Issue by andoks** [Sarcasm/run-clang-format#2]
Only python2.7, introduced by commit 01038d3b2fb8534704bf255e8a8e49a369be85b4

Work-around is to use python3

OS:
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

Python:
python --version
Python 2.7.12

````
git clone --depth 1 https://github.com/Sarcasm/run-clang-format.git run_clang_format
Cloning into 'run_clang_format'...
remote: Counting objects: 10, done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 10 (delta 0), reused 6 (delta 0), pack-reused 0
Unpacking objects: 100% (10/10), done.
Checking connectivity... done.
+ ./run_clang_format/run-clang-format.py -r <redacted>
Traceback (most recent call last):
  File "./run_clang_format/run-clang-format.py", line 253, in <module>
    sys.exit(main())
  File "./run_clang_format/run-clang-format.py", line 230, in main
    outs, errs = it.next()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 668, in next
    raise value
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 111: ordinal not in range(128)
```

**Comment by Sarcasm** [comment]
Thanks for reporting the issue.
I have committed a fix, can you confirm it's now working?
